### ISSUE TITLE
ch-21-wms-analysis.R matching on propensity score

### ISSUE THREAD

**Issue by andrasfulop10** [gabors-data-analysis/da_case_studies#32]
It seems to me that the treatment effects from propensity score matching in lines 186-187 and 215-216 are average treatment effects on the treated (ATET) and not average treatment effects (ATE) as suggested by the variable names in the code (see documentation of matchit function in R)

**Comment by gbekes** [comment]
Yes, I can see, matchit has the estimand option to be "ATE" or avg effect on the treated ="ATT".
Now added ATT as default, and ATE as optional comment.
