### ISSUE TITLE
ch23 python R2

### ISSUE THREAD

**Issue by gbekes** [gabors-data-analysis/da_case_studies#37]
R2 calculation in FE models corrected in R. Within R2 should be printed. --> check Python. 

Added a bit (not in book) that prints R2 for unweighted model --> add Python

**Comment by adamvig96** [comment]
linearmodels' [PanelOLS](https://bashtage.github.io/linearmodels/panel/panel/linearmodels.panel.model.PanelOLS.html?highlight=panelols#linearmodels.panel.model.PanelOLS) is used in [ch23 python](https://github.com/gabors-data-analysis/da_case_studies/blob/master/ch23-immunization-life/ch23-immunization-life.ipynb), and it calculates within R2 in the summary. 
However, the calculated value is different in Python than R (and book). I will check how linearmodels and R calculates R2 and why they differ.

unweighted FE is added in: https://github.com/gabors-data-analysis/da_case_studies/commit/687c718e29e7b188a10213da94b8ce9659875a1f

**Comment by adamvig96** [comment]
this is done in: https://github.com/gabors-data-analysis/da_case_studies/commit/b352d32d0714bc1152018dbc60504c14b8f62e32
