### ISSUE TITLE
world bank files ch02, ch23

### ISSUE THREAD

**Issue by gbekes** [gabors-data-analysis/da_case_studies#38]
R, Python world bank immunization files read in .dta
it should read in cleaned csv from osf. 

+add cleaners to osf that save cleaned csv--- to be read in by code in github

**Comment by adamvig96** [comment]
Done in: https://github.com/gabors-data-analysis/da_case_studies/commit/687c718e29e7b188a10213da94b8ce9659875a1f

R and Python cleaners in osf
