### ISSUE TITLE
requirements.txt looks skinny

### ISSUE THREAD

**Issue by kovacskokokornel** [gabors-data-analysis/da_case_studies#42]
It's great that exact versions are provided, but are you sure we have everything there? I am missing jupyter for instance.

**Comment by gbekes** [comment]
Not urgent, but something to check. ádám, you'll be in charge...

**Comment by kovacskokokornel** [comment]
pip freeze might be of help

**Comment by adamvig96** [comment]
this is done in https://github.com/gabors-data-analysis/da_case_studies/commit/608a500b165b34636463a00140ec8b47d67face3

pipreqsnb helped, as pip freeze checks all my installed packages
