### ISSUE TITLE
ch16 RF -- PDP todo

### ISSUE THREAD

**Issue by gbekes** [gabors-data-analysis/da_case_studies#48]
#########################################################################################
# Partial Dependence Plots -------------------------------------------------------
#########################################################################################

# TODO
# : somehow adding scale screws up. ideadlly both graphs y beween 70 and 130,
# n:accom should be 1,7 by=1

# FIXME
# should be on holdout, right? pred.grid = distinct_(data_train, "), --> pred.grid = distinct_(data_holdout, )

**Comment by adamvig96** [comment]
If i set ymin = 70 to Figure 16.3 (b) Room Type, Private room's value disappears.. In book we have 70-120 and 60-120. hm?

Also, PDP is calculated on holdout now -- will delete FIXME comment

**Comment by gbekes** [comment]
Ok
1. graphs - keep them as is
2. super, delete.

So, delete all comments, fixed
